/**
 * Clinical processing correctness (lifecycle + failure semantics) with the grounded
 * assessment (Job B). All data is synthetic; the AI SDK is mocked at `generateText`.
 */
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import request from 'supertest';

const generateText = vi.fn();
vi.mock('ai', async (importOriginal) => ({
  ...(await importOriginal<typeof import('ai')>()),
  generateText: (...args: unknown[]) => generateText(...args),
}));

import { createApp } from '../src/app';
import { cache } from '../src/middleware/cache';
import { resetRateLimits } from '../src/middleware/rateLimiter';
import { classifyAIError } from '../src/services/ai.service';
import { getFailureCounts, resetFailureCounts } from '../src/utils/failures';
import { db, faults, resetDb } from './helpers/fakeModels';
import { createTestUser } from './helpers/auth';
import { assessmentOutput, extractionOutput, isAssessmentCall, labOut } from './helpers/aiOutputs';

const app = createApp();

const EXTRACTION = extractionOutput({
  patientDetails: { name: 'Synthetic Person', age: 44, gender: 'F' },
  symptoms: ['mild headache'],
  medicines: ['paracetamol'],
  labValues: [labOut('Hemoglobin', '13.2', { unit: 'g/dL', normalRange: '12-16' })],
  fullNarrative: 'Synthetic narrative.',
});
const assessment = (riskLevel: string, riskScore: number | null, extra: Record<string, unknown> = {}) => ({
  output: assessmentOutput({ riskLevel, riskScore, ...extra }),
});

const ENV_KEYS = ['GEMINI_API_KEY', 'GOOGLE_API_KEY', 'OPENAI_API_KEY', 'ANTHROPIC_API_KEY', 'AI_TIMEOUT_MS'];
const saved: Record<string, string | undefined> = {};

let user: ReturnType<typeof createTestUser>;
const post = (body: object) => request(app).post('/api/consultations').set('Authorization', user.auth).send(body);
const stored = () => db.consultations[0];

beforeEach(() => {
  for (const key of ENV_KEYS) {
    saved[key] = process.env[key];
    delete process.env[key];
  }
  // These tests cover the processing lifecycle; the verified-reference requirement has its own tests (terminology.grounding).
  process.env.RAG_REQUIRE_REFERENCE_FOR_ASSESSMENT = 'false';
  process.env.GEMINI_API_KEY = 'test-gemini'; // → 2 candidates: gemini-3.5-flash-lite, gemini-2.5-flash-lite
  resetDb();
  cache.clear();
  resetRateLimits();
  resetFailureCounts();
  generateText.mockReset();
  user = createTestUser();
});

afterEach(() => {
  delete process.env.RAG_REQUIRE_REFERENCE_FOR_ASSESSMENT;
  for (const key of ENV_KEYS) {
    if (saved[key] === undefined) delete process.env[key];
    else process.env[key] = saved[key];
  }
});

describe('successful processing', () => {
  it('extracts (Job A), assesses (Job B) and stores a completed consultation with provenance', async () => {
    generateText.mockResolvedValueOnce({ output: EXTRACTION }).mockResolvedValueOnce(assessment('medium', 55));

    const res = await post({ rawText: 'Synthetic note: mild headache for two days.' });

    expect(res.status).toBe(201);
    expect(generateText).toHaveBeenCalledTimes(2); // exactly one extraction + one assessment call
    expect(res.body.data).toMatchObject({ status: 'completed', riskLevel: 'medium', riskScore: 55 });
    expect(res.body.data.summary).toContain('Generated by AI - Subject to Physician Review');
    expect(res.body.data.ai.extraction).toMatchObject({ source: 'model', provider: 'google', model: 'gemini-3.5-flash-lite' });
    expect(res.body.data.ai.assessment).toMatchObject({ provider: 'google', fallbackUsed: false });
    expect(res.body.data.assessment).toMatchObject({ insufficientEvidence: false, validation: { droppedCitations: 0 } });
    expect(res.headers['server-timing']).toMatch(/assessment;dur=/);
  });

  it('keeps a legitimate model-generated low-risk result distinguishable from failure', async () => {
    generateText.mockResolvedValueOnce(assessment('low', 12));
    const res = await post({ rawText: 'Routine synthetic check-up.', symptoms: ['none'] });
    expect(res.status).toBe(201);
    expect(stored()).toMatchObject({ status: 'completed', riskLevel: 'low', riskScore: 12 });
    expect(stored().failure).toBeUndefined();
  });

  it('keeps the existing client-extracted (human-in-the-loop) workflow compatible', async () => {
    generateText.mockResolvedValueOnce(assessment('high', 88));
    const res = await post({
      userId: 'ignored',
      rawText: 'Reviewed synthetic text',
      patientDetails: { name: 'Synthetic Person', age: 30, gender: 'M' },
      symptoms: ['chest tightness'],
      medicines: [],
      labValues: [{ name: 'Troponin', value: '0.9', unit: 'ng/mL', isAbnormal: true }],
    });
    expect(res.status).toBe(201);
    expect(generateText).toHaveBeenCalledTimes(1); // no server-side extraction
    expect(res.body.data).toMatchObject({ status: 'completed', riskLevel: 'high', riskScore: 88 });
    expect(res.body.data.ai.extraction).toEqual({ source: 'client' });
  });

  it('never sends the patient name to the assessment model (data minimisation)', async () => {
    generateText.mockResolvedValueOnce(assessment('low', 10));
    await post({ rawText: 'x', patientDetails: { name: 'Quorra Fictivia', age: 40 }, symptoms: ['cough'] });
    expect(generateText.mock.calls[0][0].prompt).not.toContain('Quorra');
  });
});

describe('insufficient evidence', () => {
  it('stores insufficient_evidence (no score) when the model reports it', async () => {
    generateText.mockResolvedValueOnce(assessment('insufficient_evidence', null, { insufficientEvidence: true, keyFindings: [] }));
    const res = await post({ rawText: 'Administrative synthetic note.', symptoms: ['none reported'] });
    expect(res.status).toBe(201);
    expect(stored()).toMatchObject({ status: 'completed', riskLevel: 'insufficient_evidence' });
    expect(stored().riskScore).toBeUndefined();
    expect(stored().assessment.insufficientEvidence).toBe(true);
  });

  it('downgrades an uncited low/medium/high result to insufficient_evidence — never to low', async () => {
    generateText.mockResolvedValueOnce(assessment('high', 90, { keyFindings: [{ finding: 'x', significance: 'y', evidenceIds: ['R7'] }] }));
    const res = await post({ rawText: 'x', symptoms: ['cough'] });
    expect(res.status).toBe(201);
    expect(stored()).toMatchObject({ riskLevel: 'insufficient_evidence' });
    expect(stored().assessment.validation).toMatchObject({ downgradedToInsufficient: true, droppedCitations: 1 });
  });

  it('keeps insufficient-evidence results out of the low/medium/high distribution', async () => {
    generateText.mockResolvedValueOnce(assessment('insufficient_evidence', null, { insufficientEvidence: true }));
    await post({ rawText: 'x', symptoms: ['cough'] });
    const dash = await request(app).get('/api/consultations/dashboard').set('Authorization', user.auth);
    expect(dash.body.data).toMatchObject({ total: 0, distribution: [], insufficientEvidenceCount: 1 });
  });
});

describe('fallback and failure semantics', () => {
  it('falls back to the next provider when one fails', async () => {
    generateText.mockRejectedValueOnce(Object.assign(new Error('503'), { name: 'AI_APICallError' })).mockResolvedValueOnce(assessment('medium', 45));
    const res = await post({ rawText: 'x', symptoms: ['cough'] });
    expect(res.status).toBe(201);
    expect(res.body.data.ai.assessment).toMatchObject({ model: 'gemini-2.5-flash-lite', fallbackUsed: true });
  });

  it('marks the consultation failed when every fallback provider fails — never low risk / score 0', async () => {
    generateText.mockRejectedValue(Object.assign(new Error('provider down'), { name: 'AI_APICallError' }));
    const res = await post({ rawText: 'x', symptoms: ['cough'] });
    expect(res.status).toBe(502);
    expect(res.body.data.status).toBe('failed');
    expect(stored()).toMatchObject({ status: 'failed', failure: { stage: 'assessment', category: 'provider_failure', attempts: 2 } });
    expect(stored().riskLevel).toBeUndefined();
    expect(stored().riskScore).toBeUndefined();
    expect(stored().summary).toBeUndefined();
    expect(generateText).toHaveBeenCalledTimes(2);
  });

  it('excludes failed consultations from risk statistics', async () => {
    generateText.mockRejectedValue(new Error('down'));
    await post({ rawText: 'x', symptoms: ['cough'] });
    const dash = await request(app).get('/api/consultations/dashboard').set('Authorization', user.auth);
    expect(dash.body.data).toMatchObject({ total: 0, distribution: [], failedCount: 1 });
  });

  it('treats malformed structured output (unsupported enum) as a schema validation failure', async () => {
    generateText.mockResolvedValue(assessment('critical', 50));
    const res = await post({ rawText: 'x', symptoms: ['cough'] });
    expect(res.status).toBe(502);
    expect(stored().failure).toMatchObject({ stage: 'assessment', category: 'schema_validation_failure' });
  });

  it('rejects output missing required fields or with impossible values', async () => {
    generateText
      .mockResolvedValueOnce({ output: { summary: 'Synthetic text only', riskLevel: 'low' } })
      .mockResolvedValueOnce(assessment('high', 140));
    const res = await post({ rawText: 'x', symptoms: ['cough'] });
    expect(res.status).toBe(502);
    expect(stored().failure.category).toBe('schema_validation_failure');
  });

  it('rejects an empty summary even when enum/score are valid', async () => {
    generateText.mockResolvedValue(assessment('low', 5, { summary: '   ' }));
    const res = await post({ rawText: 'x', symptoms: ['cough'] });
    expect(res.status).toBe(502);
    expect(stored().status).toBe('failed');
  });

  it('records extraction success + assessment failure at the assessment stage, keeping the input', async () => {
    generateText.mockImplementation(async (opts: { system?: string }) => {
      if (isAssessmentCall(opts)) throw new Error('assessment provider down');
      return { output: EXTRACTION };
    });
    const res = await post({ rawText: 'Synthetic note: mild headache.' });
    expect(res.status).toBe(502);
    expect(stored()).toMatchObject({ status: 'failed', rawText: 'Synthetic note: mild headache.', failure: { stage: 'assessment' } });
  });

  it('records extraction failure at the extraction stage', async () => {
    generateText.mockRejectedValue(new Error('down'));
    const res = await post({ rawText: 'Synthetic note only' });
    expect(res.status).toBe(502);
    expect(stored().failure.stage).toBe('extraction');
  });

  it('times out hanging providers and records a timeout failure', async () => {
    process.env.AI_TIMEOUT_MS = '30';
    generateText.mockImplementation(
      (opts: { abortSignal: AbortSignal }) =>
        new Promise((_resolve, reject) => opts.abortSignal.addEventListener('abort', () => reject(opts.abortSignal.reason)))
    );
    const started = Date.now();
    const res = await post({ rawText: 'x', symptoms: ['cough'] });
    expect(res.status).toBe(502);
    expect(Date.now() - started).toBeLessThan(2_000);
    expect(stored().failure.category).toBe('provider_timeout');
  });

  it('records rate limiting explicitly', async () => {
    generateText.mockRejectedValue(Object.assign(new Error('quota'), { name: 'AI_APICallError', statusCode: 429 }));
    const res = await post({ rawText: 'x', symptoms: ['cough'] });
    expect(res.status).toBe(502);
    expect(stored().failure.category).toBe('provider_rate_limited');
  });

  it('marks the consultation failed when saving the result fails after a successful assessment', async () => {
    generateText.mockResolvedValueOnce(assessment('medium', 50));
    faults.failNextConsultationUpdate = true;
    const res = await post({ rawText: 'x', symptoms: ['cough'] });
    expect(res.status).toBe(500);
    expect(stored()).toMatchObject({ status: 'failed', failure: { stage: 'persistence', category: 'persistence_failure' } });
    expect(stored().riskLevel).toBeUndefined();
  });

  it('returns 500 without calling AI when the initial record cannot be created', async () => {
    faults.failConsultationCreate = true;
    const res = await post({ rawText: 'x', symptoms: ['cough'] });
    expect(res.status).toBe(500);
    expect(generateText).not.toHaveBeenCalled();
  });

  it('marks the consultation failed with configuration_error when no provider is configured', async () => {
    delete process.env.GEMINI_API_KEY;
    const res = await post({ rawText: 'x', symptoms: ['cough'] });
    expect(res.status).toBe(503);
    expect(stored().failure.category).toBe('configuration_error');
  });

  it('counts categorised failures', async () => {
    generateText.mockRejectedValue(new Error('down'));
    await post({ rawText: 'x', symptoms: ['cough'] });
    expect(getFailureCounts().provider_failure).toBe(1);
  });
});

describe('risk score safety', () => {
  it('stores band-normalised scores with a provenance flag (category authoritative)', async () => {
    generateText.mockResolvedValueOnce(assessment('high', 20));
    const res = await post({ rawText: 'x', symptoms: ['cough'] });
    expect(res.body.data).toMatchObject({ riskLevel: 'high', riskScore: 70 });
    expect(res.body.data.assessment.validation.riskScoreAdjusted).toBe(true);
  });
});

describe('error classification', () => {
  it('maps SDK errors onto failure categories', () => {
    const named = (name: string, extra: object = {}) => Object.assign(new Error(name), { name, ...extra });
    expect(classifyAIError(named('TimeoutError'))).toBe('provider_timeout');
    expect(classifyAIError(named('AbortError'))).toBe('provider_timeout');
    expect(classifyAIError(named('AI_NoObjectGeneratedError'))).toBe('schema_validation_failure');
    expect(classifyAIError(named('AI_APICallError'))).toBe('provider_failure');
    expect(classifyAIError(named('AI_APICallError', { statusCode: 429 }))).toBe('provider_rate_limited');
    expect(classifyAIError(named('AI_APICallError', { statusCode: 404 }))).toBe('model_unavailable');
    expect(classifyAIError(Object.assign(named('AI_RetryError'), { lastError: named('TimeoutError') }))).toBe('provider_timeout');
  });
});
