/** Factories for SYNTHETIC mocked model outputs (schema-complete). */

export const labOut = (name: string, value: string, extra: Record<string, unknown> = {}) => ({
  name,
  value,
  unit: '',
  normalRange: '',
  isAbnormal: false,
  date: '',
  ...extra,
});

export const extractionOutput = (overrides: Record<string, unknown> = {}) => ({
  patientDetails: { name: '', age: null, gender: '' },
  symptoms: [],
  medicines: [],
  labValues: [],
  dates: [],
  diagnosesMentioned: [],
  measurements: [],
  imagingFindings: [],
  reportRiskScores: [],
  doctorNotes: '',
  extractionLimitations: [],
  fullNarrative: '',
  ...overrides,
});

export const assessmentOutput = (overrides: Record<string, unknown> = {}) => ({
  riskLevel: 'medium',
  riskScore: 50,
  summary: 'Synthetic assessment summary for clinician review.',
  keyFindings: [{ finding: 'Synthetic finding', significance: 'Synthetic significance', evidenceIds: ['F1'] }],
  supportingEvidence: [],
  patientEvidence: [],
  uncertainty: '',
  insufficientEvidence: false,
  ...overrides,
});

/** A ClinicalAssessment as returned by assessRisk (for mocking the service). */
export const fakeClinicalAssessment = (riskLevel = 'medium', riskScore: number | undefined = 50) => ({
  riskLevel,
  ...(riskScore !== undefined ? { riskScore } : {}),
  summary: 'Synthetic summary. Generated by AI - Subject to Physician Review',
  keyFindings: [],
  uncertainty: '',
  insufficientEvidence: riskLevel === 'insufficient_evidence',
  findingsCited: [],
  patientEvidence: [],
  medicalReferencesUsed: [],
  retrieval: { queries: 0, patientStatus: 'no_documents', referenceStatus: 'no_sources', patientRetrieved: 0, referencesRetrieved: 0, referencesCited: 0 },
  validation: { droppedCitations: 0, riskScoreAdjusted: false, downgradedToInsufficient: false },
  provider: 'google',
  model: 'test-model',
  fallbackUsed: false,
});

/** True when a mocked generateText call is the clinical assessment (Job B). */
export const isAssessmentCall = (opts: { system?: string }) => Boolean(opts.system?.includes('evidence-grounded clinical information assistant'));
/** True when a mocked generateText call is medical Q&A. */
export const isQACall = (opts: { system?: string }) => Boolean(opts.system?.includes('evidence-grounded medical information assistant'));
/** True when a mocked generateText call is extraction (Job A). */
export const isExtractionCall = (opts: { system?: string }) => Boolean(opts.system?.includes('clinical document extraction assistant'));
/** True when a mocked generateText call is the terminology explanation. */
export const isTerminologyCall = (opts: { system?: string }) => Boolean(opts.system?.includes('explain medical terminology in plain language'));
